name: Python App Workflow

on:
  workflow_dispatch:
    inputs:
      levels:
        description: 'Number of directory levels to display with tree command'
        required: true
        default: '2'

jobs:
  install-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python app
        run: python app.py

      - name: List files
        run: ls -al

  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files
        run: ls -al

  run-tree-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tree command
        run: |
          sudo apt-get install -y tree
          tree -L ${{ github.event.inputs.levels }}
